export const FORM_ERROR = "FINAL_FORM/form-error";
export const ARRAY_ERROR = "FINAL_FORM/array-error";

export const fieldSubscriptionItems = [
  "active",
  "data",
  "dirty",
  "dirtySinceLastSubmit",
  "error",
  "initial",
  "invalid",
  "length",
  "modified",
  "modifiedSinceLastSubmit",
  "pristine",
  "submitError",
  "submitFailed",
  "submitSucceeded",
  "submitting",
  "touched",
  "valid",
  "value",
  "visited",
  "validating",
];

export const formSubscriptionItems = [
  "active",
  "dirty",
  "dirtyFields",
  "dirtyFieldsSinceLastSubmit",
  "dirtySinceLastSubmit",
  "error",
  "errors",
  "hasSubmitErrors",
  "hasValidationErrors",
  "initialValues",
  "invalid",
  "modified",
  "modifiedSinceLastSubmit",
  "pristine",
  "submitting",
  "submitError",
  "submitErrors",
  "submitFailed",
  "submitSucceeded",
  "touched",
  "valid",
  "validating",
  "values",
  "visited",
];
